### ISSUE TITLE
Doesn't work in Windows

### ISSUE THREAD

**Issue by mohanraj-r** [pnpnpn/timeout-decorator#1]
Thank you for this work.

Is this expected to work in Windows ?
I got  the following error

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\Python27\lib\site-packages\timeout_decorator\timeout_decorator.py", line 32, in new_f
    old = signal.signal(signal.SIGALRM, handler)
AttributeError: 'module' object has no attribute 'SIGALRM'
```

I guess `signal` module in Windows [doesn't have the SIGALRM](http://stackoverflow.com/questions/4511732/alarm-function-on-linux-and-windows-cant-find-a-equivalent-for-windows-c)

It would be helpful if you can edit the Readme and/or put a os check in the code.

Thanks,

**Comment by pombredanne** [comment]
If this can help, check this: https://github.com/nexB/scancode-toolkit/blob/c4b1e9d7da546cf252a01f6fe42c16631df7e630/src/scancode/interrupt.py

It runs on linux/mac/windows thanks to this: https://github.com/nexB/scancode-toolkit/tree/c4b1e9d7da546cf252a01f6fe42c16631df7e630/src/scancode/timeouts

... borrowed from https://github.com/robotframework/robotframework by @pekkaklarck and @mkorpela 

Actually https://github.com/robotframework/robotframework/tree/dc0581a46c5da6f632c7e505fafa22046a84ba3a/src/robot/running/timeouts also supports Jython and IronPython.
