### ISSUE TITLE
Missing git version tags

### ISSUE THREAD

**Issue by kloczek** [pnpnpn/timeout-decorator#81]
According to https://pypi.org/project/timeout-decorator/ latest version is 0.5.0 but here latest git tag i 0.1.0.
Is it possible to add at least last version tag? 🤔

**Comment by kloczek** [comment]
Gentle ping .. 🤔

**Comment by pnpnpn** [comment]
Done: https://github.com/pnpnpn/timeout-decorator/releases/tag/0.5.0 Thanks!
