### ISSUE TITLE
Release Python 3 support

### ISSUE THREAD

**Issue by pimterry** [pnpnpn/timeout-decorator#9]
I have a project on which I'd like to use this, but it's a bit of a hassle to do so, because the published version doesn't work with Python 3.

I just took a look into fixing this, but it looks like it was actually already fixed in the codebase here a little while back, and just hasn't made it downstream yet. Any chance you could release a new version please that includes that fix?

**Comment by pnpnpn** [comment]
Done. https://pypi.python.org/pypi/timeout-decorator/0.2.0

**Comment by pimterry** [comment]
Awesome, thanks for sorting that so quickly!
